[package]
name = "separating_modules_into_different_files"
version = "0.1.0"
authors = ["Pierre-Antoine Passet <pa@passet.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
